[tool.poetry]
name = "rulerascal"
version = "0.1.0"
description = ""
authors = ["Bence Nagy <nagy@bence.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiogpt = "^0.0.3"
httpx = "^0.23.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
