rules:
- id: net-webconfig-debug
  patterns:
  - pattern: |
      <compilation ... debug = "true" ... />
  - pattern-inside: |
      <system.web>
        ...
      </system.web>
  message: >-
    ASP.NET applications built with `debug` set to true in production may leak debug information to attackers.
    Debug mode also affects performance and reliability.
    Set `debug` to `false` or remove it from `<compilation ... />`
  languages: [generic]
  severity: WARNING
  paths:
    include:
      - "*web.config*"
  metadata: 
    category: security
    cwe: "CWE-11: ASP.NET Misconfiguration: Creating Debug Binary"
    owasp: 'A5: Security Misconfiguration'
    technology:
    - .net
    confidence: HIGH
    references:
      - https://web.archive.org/web/20190919105353/https://blogs.msdn.microsoft.com/prashant_upadhyay/2011/07/14/why-debugfalse-in-asp-net-applications-in-production-environment/
      - https://msdn.microsoft.com/en-us/library/e8z01xdh.aspx