# ruleid: localhost-base-url
baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Example"
theme = "ananke"
uglyurls = true

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
Paginate = 10
enableRobotsTXT = true

[menu]
[[menu.main]]
identifer = "about"
name = "About"
url = "/about.html"
weight = -110
