rules:
- id: aws-lambda-environment-unencrypted
  patterns:
    - pattern: |
        resource "aws_lambda_function" $ANYTHING {
          ...
        }
    - pattern-not-inside: |
        resource "aws_lambda_function" $ANYTHING {
          ...
          kms_key_id = ...
          ...
        }
  message: The AWS Lambda Environment is unencrypted. The AWS KMS encryption key protects environment in the Lambda. To create your own, create a aws_kms_key resource or use the ARN string of a key in your account.
  languages: [hcl]
  severity: WARNING
  metadata:
    owasp:
    - A02:2021 - Cryptographic Failures
    cwe: |
      CWE-311: Missing Encryption of Sensitive Data
    technology:
      - aws
      - terraform
    category: security
