# Flask check3: Flask application app.run best practices https://flask.palletsprojects.com/en/1.1.x/api/?highlight=run#flask.Flask.run
rules:
  # . Rules for app.run() parameters
  - id: avoid_app_run_with_bad_host
    patterns:
      - pattern-either:
        - pattern: app.run(..., host="0.0.0.0", ...)
        - pattern: app.run(..., "0.0.0.0", ...)
    message: "Running flask app with host 0.0.0.0 could expose the server publicly."
    languages: [python]
    severity: WARNING
