version: "3.9"
services:
  # ok: privileged-service
  web:
    image: nginx:alpine
  worker:
    image: my-worker-image:latest
    # ruleid:privileged-service
    privileged: true
  # ok: privileged-service
  db:
    image: mysql
