---
version: 2
updates:
  # ok: dependabot-missing-cooldown
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

---
version: 2
updates:
  # ok: dependabot-missing-cooldown
  - package-ecosystem: "pip"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
  # ok: dependabot-missing-cooldown
  - package-ecosystem: "docker"
    directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

---
version: 2
updates:
  # ok: dependabot-missing-cooldown
  - package-ecosystem: "pip"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
  # ruleid: dependabot-missing-cooldown
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

---
version: 2
updates:
  # ruleid: dependabot-missing-cooldown
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

---
version: 2
updates:
  # ok: dependabot-missing-cooldown
  - package-ecosystem: "pip"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"

---
version: 2
updates:
  # ok: dependabot-missing-cooldown
  - package-ecosystem: "pip"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"

---
version: 2
updates:
  # ok: dependabot-missing-cooldown
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    cooldown:
      # ruleid: dependabot-missing-cooldown
      default-days: 3

---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    cooldown:
      # ruleid: dependabot-missing-cooldown
      default-days: null

---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    cooldown:
      # ruleid: dependabot-missing-cooldown
      default-days: "banana"
