apiVersion: v1
kind: Pod
spec:
  containers:
    # ruleid: allow-privilege-escalation-no-securitycontext
    - name: nginx
      securityContext:
        allowPrivilegeEscalation: false
      image: nginx
    # ok: allow-privilege-escalation-no-securitycontext
    - name: postgres
      image: postgres
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
    # ok: allow-privilege-escalation-no-securitycontext
    - name: redis
      image: redis
      securityContext:
        allowPrivilegeEscalation: true
    # ok: allow-privilege-escalation-no-securitycontext
    - name: haproxy
      image: haproxy
      securityContext:
        allowPrivilegeEscalation: false
