apiVersion: v1
kind: Pod
spec:
  containers:
    # ok: allow-privilege-escalation
    - name: nginx
      image: nginx
    - name: postgres
      image: postgres
    # ruleid: allow-privilege-escalation
      securityContext:
        allowPrivilegeEscalation: false #:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
    # ok: allow-privilege-escalation
    - name: redis
      image: redis
      securityContext:
        allowPrivilegeEscalation: true
    # ok: allow-privilege-escalation
    - name: haproxy
      image: haproxy
      securityContext:
        allowPrivilegeEscalation: false
