apiVersion: v1
kind: Pod
spec:
  containers:
    # ok: allow-privilege-escalation-true
    - name: nginx
      image: nginx
    # ok: allow-privilege-escalation-true
    - name: postgres
      image: postgres
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
    - name: redis
      image: redis
      securityContext:
        # ruleid: allow-privilege-escalation-true
        allowPrivilegeEscalation: false
    - name: redis
      securityContext:
        # ruleid: allow-privilege-escalation-true
        allowPrivilegeEscalation: false
      image: redis
    - securityContext:
        # ruleid: allow-privilege-escalation-true
        allowPrivilegeEscalation: false
      name: redis
      image: redis
    # ok: allow-privilege-escalation-true
    - name: haproxy
      image: haproxy
      securityContext:
        allowPrivilegeEscalation: false
