---
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: redis
      image: redis
      securityContext:
        # ruleid: run-as-non-root-unsafe-value
        runAsNonRoot: true
    - name: haproxy
      image: haproxy
      securityContext:
        # ok: run-as-non-root-unsafe-value
        runAsNonRoot: true
---
apiVersion: v1
kind: Pod
spec:
  securityContext:
    # ruleid: run-as-non-root-unsafe-value
    runAsNonRoot: true
  containers:
    - name: redis
      image: redis
    - name: haproxy
      image: haproxy
      securityContext:
        # ok: run-as-non-root-unsafe-value
        runAsNonRoot: true
---
apiVersion: v1
kind: Pod
spec:
  securityContext:
    # ok: run-as-non-root-unsafe-value
    runAsNonRoot: true
  containers:
    - name: redis
      image: redis
    - name: haproxy
      image: haproxy
      securityContext:
        # ruleid: run-as-non-root-unsafe-value
        runAsNonRoot: true
