on: pull_request

name: command-processing-test
jobs:
  dangerous-job:
    name: example
    runs-on: ubuntu-latest
    steps:
      - name: dont-do-this
        env:
          # ruleid: allowed-unsecure-commands
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          echo "don't do this"
  another-dangerous-job:
    name: example2
    runs-on: ubuntu-latest
    env:
      # ruleid: allowed-unsecure-commands
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: or-this
        run: |
          echo "seriously, dont"
  this-is-ok:
    name: example3
    runs-on: ubuntu-latest
    env: PREFIX = "~~^_^~~"
    run: |
      echo "$PREFIX hello"
