name: CI

on:
  push:
    branches: [main]

jobs:
  call-reusable-inherit:
    uses: octo-org/example-repo/.github/workflows/reusable.yml@main
    # ruleid: secrets-inherit
    secrets: inherit

  call-reusable-inherit-no-with:
    uses: ./.github/workflows/local-reusable.yml
    # ruleid: secrets-inherit
    secrets: inherit

  call-reusable-inherit-with-inputs:
    uses: octo-org/example-repo/.github/workflows/reusable.yml@v1
    with:
      config-path: .github/labeler.yml
    # ruleid: secrets-inherit
    secrets: inherit

  call-reusable-explicit-secrets:
    uses: octo-org/example-repo/.github/workflows/reusable.yml@main
    # ok: secrets-inherit
    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}

  call-reusable-no-secrets:
    uses: octo-org/example-repo/.github/workflows/reusable.yml@main
    with:
      config-path: .github/labeler.yml

  normal-job-no-secrets-keyword:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello"
