#!/usr/bin/env python
import os
import subprocess
import sys


# Apply a patch if "$SEMGREP_OLD_VERSION" is less than `needed_until`
def patch(needed_until, patch_filename):
    historical_version = tuple(map(int, os.environ["SEMGREP_OLD_VERSION"].split(".")))

    if historical_version > needed_until:
        print(
            f"{patch_filename} is not needed anymore. Please delete the logic from scripts/apply-historical-patches"
        )
        sys.exit(1)

    patch_path = os.path.join("scripts/historical-semgrep-patches", patch_filename)
    print(f"Applying {patch_path}")
    try:
        subprocess.run(["patch", "-p0", "--input", patch_path], check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error applying {patch_path}:", e)


root_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
os.chdir(root_dir)

patch((1, 36, 0), "case-insensitive-php.patch")
