rules:
- id: wildcard-postmessage-configuration
  languages:
  - javascript
  - typescript
  message: "The target origin of the window.postMessage() API is set to \"*\". This could allow for information disclosure\
    \ due to the possibility of any origin allowed to receive the message.\n"
  metadata:
    cwe: 'CWE-345: Insufficient Verification of Data Authenticity'
    owasp: 'A6: Sensitive Data Exposure'
  patterns:
  - pattern-either:
    - pattern: "$OBJECT.postMessage(...,'*')\n"
  severity: WARNING
