rules:
  - id: cors-misconfiguration
    mode: taint
    languages:
      - js
      - typescript
    metadata:
      owasp: "A1: Injection"
      cwe: "CWE-346: Origin Validation Error"
      category: security
      technology:
        - express
    message: >-
      By letting user input control CORS parameters, there is a risk that software does not properly verify that the source
      of data or communication is valid. Use literal values for CORS settings.
    severity: WARNING
    pattern-sinks:
      - patterns:
          - pattern-either:
              - pattern: $RES.set($HEADER, ...)
              - pattern: $RES.header($HEADER, ...)
              - pattern: $RES.setHeader($HEADER, ...)
              - pattern: |
                  $RES.set({$HEADER: ...}, ...)
              - pattern: |
                  $RES.writeHead($STATUS, {$HEADER: ...}, ...)
          - metavariable-regex:
              metavariable: $HEADER
              regex: .*(Access-Control-Allow-Origin|access-control-allow-origin).*
    pattern-sources:
      - patterns:
          - pattern-either:
              - pattern-inside: function ... ($REQ, $RES) {...}
              - pattern-inside: function ... ($REQ, $RES, $NEXT) {...}
              - patterns:
                  - pattern-inside: $APP.$METHOD(..., function $FUNC($REQ, $RES) {...})
                  - metavariable-regex:
                      metavariable: $METHOD
                      regex: ^(get|post|put|head|delete|options)
          - pattern-either:
              - pattern: $REQ.query
              - pattern: $REQ.body
              - pattern: $REQ.params
              - pattern: $REQ.cookies
              - pattern: $REQ.headers
      - patterns:
          - pattern-either:
              - pattern-inside: |
                  ({ $REQ }: Request,$RES: Response, $NEXT: NextFunction) =>
                  {...}
              - pattern-inside: |
                  ({ $REQ }: Request,$RES: Response) => {...}
          - focus-metavariable: $REQ
          - pattern-either:
              - pattern: params
              - pattern: query
              - pattern: cookies
              - pattern: headers
              - pattern: body