rules:
- id: misconfigured-lockout-option
  patterns:
  - pattern-either:
    - pattern: |
        $SIGNIN.PasswordSignInAsync(...,lockoutOnFailure: false,...);
    - pattern: |
        $SIGNIN.CheckPasswordSignInAsync(...,lockoutOnFailure: false,...);
  - pattern-inside: |
      public async $TYPE<IActionResult> $METHOD(...) {
        ...
      }
  message: >-
    A misconfigured lockout mechanism allows an attacker to execute brute-force
    attacks. Account lockout must be correctly configured and enabled to prevent these
    attacks.
  metadata:
    category: security
    technology:
    - dotnet
    owasp:
    - "A07:2021 - Identification and Authentication Failures"
    cwe: 'CWE-307: Improper Restriction of Excessive Authentication Attempts'
    references:
    - https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures
    - https://cwe.mitre.org/data/definitions/307.html
  languages:
  - csharp
  severity: WARNING
