name: format-rules

on:
  workflow_dispatch:
  pull_request_review:
    types:
      - submitted
    branches:
      - develop
      - release

jobs:
  format-rules:
    name: format-rules
    if: github.event.review.state == 'approved' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "17.3.0"
      - name: install prettier
        run: npm install prettier
      - name: get changed files
        id: changes
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          THIS_SHA: ${{ github.sha }}
        run: |
          echo "::set-output name=changed::$(git diff --name-only --diff-filter=ACMRT $BASE_SHA $THIS_SHA | grep .yaml$ | xargs)" 
      - name: format incoming rules
        id: format
        env:
          CHANGED: ${{ steps.changes.outputs.changed }}
        run: npx prettier --write $CHANGED
      - name: commit formatted files
        if: ${{ success() }}
        id: commit
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
          CHANGED: ${{ steps.changes.outputs.changed }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout "$BRANCH"
          git add $CHANGED
          git commit -m "Formatted new rules" --no-verify
          git push origin "$BRANCH"