name: pre-commit

on:
  pull_request:
  push:
    branches: [master, develop]

jobs:
  pre-commit:
    uses: semgrep/release-workflows/.github/workflows/pre-commit.yaml@c04907222197635bc8fc0d80b1d5fec8f945eb43 # develop
    with:
      skip: yamlfmt
