name: semgrep-rules-test

on:
  pull_request:
    branches:
    - release
  push:
    branches:
    - release

jobs:
  test-latest:
    name: rules-test-latest
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.10'
    - name: install semgrep via pip
      run: pip3 install semgrep
    - name: remove stats directory
      run: rm -rf stats
    - name: remove rules requiring Semgrep Pro
      run: rm -rf apex elixir
    - name: validate rules
      run: semgrep validate .
    - name: run semgrep test
      run: semgrep test .
