name: sgrep-develop

on: [push]

jobs:
  test-develop:
    runs-on: ubuntu-latest
    name: test-develop
    steps:
      - uses: actions/checkout@v2
      - name: test
        id: test
        uses: returntocorp/sgrep-rules-test-action-develop@master
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: tests
          path: ${{ steps.test.outputs.output_dir }}
